language: node_js
node_js:
  - '0.8'
  - '0.10'
before_install:
  - currentfolder=${PWD##*/}
  - if [ "$currentfolder" != 'generator-kendo-ui' ]; then cd .. && eval "mv $currentfolder generator-kendo-ui" && cd generator-kendo-ui; fi

